const progress=document.getElementById('progress');
const cursor=document.querySelector('.cursor-glow');
const menuToggle=document.getElementById('menuToggle');
const navLinks=document.getElementById('navLinks');
const reveals=document.querySelectorAll('.reveal');
const updateProgress=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=(max>0?(window.scrollY/max)*100:0)+'%'};
window.addEventListener('scroll',updateProgress,{passive:true});
updateProgress();
if(cursor) window.addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});
menuToggle?.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open)});
navLinks?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.12});
reveals.forEach(el=>observer.observe(el));
